#!/usr/bin/env tsx
// Generate docs/cli-reference.generated.md from the CommandSpec single source.
//
// Run via tsx so it imports the TypeScript spec directly — no dist build
// needed (matches the scripts/harness/run.ts precedent).
//
//   pnpm gen:cli-reference     write the file
//   pnpm check:cli-reference   regenerate in memory and fail on drift (CI)
//
// --check compares generated content to the committed file directly, so it
// works on a dirty working tree (unlike `git diff --exit-code`).

import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import { TASK_SPECS } from "../src/cli/spec/task.ts";
import { PLAN_SPECS, PLAN_SPEC_ORDER } from "../src/cli/spec/plan.ts";
import { ROOT_SPECS } from "../src/cli/spec/root.ts";
import { renderReference } from "../src/cli/spec/render.ts";

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const OUT = resolve(repoRoot, "docs/cli-reference.generated.md");

const BANNER = [
  "<!-- DO NOT EDIT — generated by scripts/gen-cli-reference.ts.",
  "     Run `pnpm gen:cli-reference` after changing a CommandSpec. -->",
].join("\n");

function render(): string {
  const sections: string[] = [
    BANNER,
    "",
    "# CLI reference (generated)",
    "",
    "Per-command flags, usage, and examples for the generated CLI surfaces,",
    "derived from the `CommandSpec` single source (`src/cli/spec/`). Some",
    "clusters are not generated yet — their flags live in each command's `--help`,",
    "and their semantics in",
    "[`cli-contract.md`](cli-contract.md). The stable CLI contract — JSON",
    "envelope, exit codes, error codes, stability taxonomy — also lives in",
    "[`cli-contract.md`](cli-contract.md).",
    "",
  ];

  sections.push("## Top-level commands", "");
  sections.push(renderReference(ROOT_SPECS.verify), "");
  sections.push("## Task commands", "");

  // Deterministic order: lifecycle reading order, then any others by key.
  const order = [
    "add",
    "context",
    "prepare",
    "start",
    "status",
    "block",
    "resume",
    "runbook",
    "complete",
    "record-done",
    "finalize",
  ];
  const keys = [
    ...order.filter((k) => k in TASK_SPECS),
    ...Object.keys(TASK_SPECS).filter((k) => !order.includes(k)),
  ];
  for (const key of keys) {
    sections.push(renderReference(TASK_SPECS[key]!), "");
  }

  sections.push("## Plan commands", "");
  for (const key of PLAN_SPEC_ORDER) {
    sections.push(renderReference(PLAN_SPECS[key]!), "");
  }
  sections.push(
    "### `plan import`",
    "",
    "`code-pact plan import <file> [options]` is an alias for `code-pact phase import <file> [options]`. Its flag surface is intentionally not duplicated here; run `code-pact phase import --help` for the source command until the phase cluster is CommandSpec-backed.",
    "",
  );

  return `${sections.join("\n").trimEnd()}\n`;
}

const content = render();
const check = process.argv.includes("--check");

if (check) {
  let current: string;
  try {
    current = readFileSync(OUT, "utf8");
  } catch {
    current = "";
  }
  if (current !== content) {
    process.stderr.write(
      "check:cli-reference: docs/cli-reference.generated.md is stale.\n" +
        "Run `pnpm gen:cli-reference` and commit the result.\n",
    );
    process.exit(1);
  }
  process.stdout.write("check:cli-reference: OK — generated reference is up to date.\n");
} else {
  writeFileSync(OUT, content);
  process.stdout.write(`Wrote ${OUT}\n`);
}
